DROP TABLE IF EXISTS `#__0001_kontorahmen`;
DROP TABLE IF EXISTS `#__0001_konto`;
DROP TABLE IF EXISTS `#__0001_buchung`;
DROP TABLE IF EXISTS `#__0001_buchungdetail`;
DROP TABLE IF EXISTS `#__0001_cerp_customers`;
DROP TABLE IF EXISTS `#__0001_cerp_product`;
DROP TABLE IF EXISTS `#__0001_cerp_configpersonal` ;
DROP TABLE IF EXISTS `#__0001_cerp_configglobal`;
DROP TABLE IF EXISTS `#__0001_cerp_factura`;
DROP TABLE IF EXISTS `#__0001_cerp_facturarun`;
DROP TABLE IF EXISTS `#__0001_cerp_facturastate`;
DROP TABLE IF EXISTS `#__0001_cerp_template`;
DROP TABLE IF EXISTS `#__0001_davUserCat` ;
DROP TABLE IF EXISTS `#__0001_cerp_maildistributer`;
DROP TABLE IF EXISTS `#__0001_cerp_mailwhitelist`;
